name: Deploy Node Application

on:
  push:
    branches:
      - main

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source 
      uses: actions/checkout@v4
    - name: Login to docker hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/puk_backend .
    - name: Push image to docker hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/puk_backend:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Docker Image
        uses: docker pull ${{ secrets.DOCKER_USERNAME }}/puk_backend:latest
      - name: Run Docker Container
        run: |
            docker run -d -p 9000:9000 \
            --name puk_backend-container \
            -e PORT=9000 \
            -e MONGODB_URI=${{ secrets.MONGODB_URI }} \
            -e JWT_REFRESH_SECRET=${{ secrets.JWT_REFRESH_SECRET }} \
            -e JWT_ACCESS_SECRET=${{ secrets.JWT_ACCESS_SECRET }}
